name: score_square
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^1.0.1
  animated_bottom_navigation_bar: ^0.3.2
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.0
  crypto: ^3.0.0
  cupertino_icons: ^1.0.0
  day_night_switcher: ^0.2.0+1
  equatable: ^2.0.3
  expansion_tile_card: ^2.0.0
  firebase_auth: ^3.2.0
  firebase_auth_web: ^3.2.0
  firebase_core: ^1.0.4
  firebase_messaging: ^11.1.0
  flutter_layout_grid: ^1.0.3
  flutter_phoenix: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_speed_dial: ^4.6.6
  firebase_storage: ^10.1.0
  flutter_bloc: ^8.0.0
  flutterfire_ui: ^0.2.0+2
  getwidget: ^2.0.4
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.1
  http: ^0.13.1
  image_cropper: ^1.3.1
  image_downloader: ^0.31.0
  image_picker: ^0.8.4+4
  image_stack: ^2.0.1
  intl: ^0.17.0
  launch_review: ^3.0.1
  material_design_icons_flutter: ^5.0.6295
  new_version: ^0.2.0
  package_info: ^2.0.2
  pagination_view:
  persistent_bottom_nav_bar: ^4.0.2
  rxdart: ^0.27.2
  share: ^2.0.4
  shared_preferences: ^2.0.5
  timeago: ^3.1.0
  tutorial_coach_mark: ^1.1.1
  url_launcher: ^6.0.3
  universal_io: ^2.0.4
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat-Regular.ttf
  #         style: italic
